### ISSUE TITLE
Errores del proyecto

### ISSUE THREAD

**Issue by ushieru** [Tamagochi02/Proyecto-Responsivo#1]
# Static Files

https://expressjs.com/en/starter/static-files.html

Los archivos estaticos son colocados en una carpeta y estos seran descargados por el archivo web que los pida.

En este caso los estilos y el codigo de js de nuestra pagina seran servidos como estaticos.

```js
app.use(express.static('public')); // Esta linea nos permite servir archivos staticos desde la carpeta public

app.get('/', (req, res) => {
    return res.sendFile(path.join(__dirname, '/index.html')); // Envia el index.html
})
```

### Actualizamos nuestro <head> en el HTML
```html
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Formulario responsivo</title>

    <!-- Estas lineas se encargaran de bajar nuestros arcivhos estaticos -->
    <link rel="stylesheet" href="/styles.css"> 
    <script src="/index.js"></script>
</head>
```

Creamos una carpeta **public** y ahi metemos el contenido que teniamos en nuestro HTML
![image](https://user-images.githubusercontent.com/32021976/170143407-adf4b3bd-c240-49ea-a4b1-fbae23d61696.png)

Styles llevara todo lo que estaba en nuestras etiquetas de style.

En index.js ira todo nuestro codigo que teniamos en la etiqueta de script. Este tenia algunos detalles ashi que pegare aqui los cambios con sus comentarios.

> public/index.js
```js
// Aqui va toda la logica de tu pagina
const getData = () => {
    var name = document.getElementById("nombre").value;
    // document.getElementById("valueInput").innerHTML = inputValue; // Para mostrar en la pagina
    var date = document.getElementById("fecha").value;
    var color = document.getElementById("color").value;
    var cal = document.getElementById("calificacion").value;
    var tel = document.getElementById("telefono").value;
    var emaill = document.getElementById("email").value;
    var file = document.getElementById("archivo").value;
    var language = document.getElementById("lenguaje").value;
    // console.log(name)
    // console.log(calificacion) 
    // console.log(archivo)
    // console.log(color)
    // console.log(email)
    // console.log(date)
    // console.log(lenguaje)
    // console.log(telefono)

    const data = { name, date, color, cal, tel, emaill, file, language };
    // console.log(data)

    const options = {
        method: 'POST',
        // Headers: { headers no va en mayuscula
        headers: { // va en minuscula
            'Content-Type': 'application/json'
        },
        body: JSON.stringify(data)
    };

    fetch('/user', options)
        .then(response => response.json()) // Transforma de stream a json los datos
        .then(response => console.log(response)) // Ahora si los podemos imprimir en consola
}
```

# API REST

Elimine la carpeta de api y movi **nedb.js** a un index.js en la raiz del proyecto.
Pego aqui los cambios con sus comentarios.

> index.js
```js
const express = require('express');
const app = express();
const Nedb = require('nedb')
const path = require('path')

app.use(express.static('public')); // Esta linea nos permite servir archivos staticos desde la carpeta public

const db = new Nedb({ // Crear archivo database
    filename: path.join(__dirname/*--> Carpeta en la que estoy parado*/, "usuarios.db"),
    autoload: true
})

app.get('/', (req, res) => {
    return res.sendFile(path.join(__dirname, '/index.html')); // Envia el index.html
})

/**
 * Hay que decirle a express que queremos usar JSON a partir de este endpoint
 * Para que pueda leer el payload de tu request
 */
app.use(express.json());

/** el metodo post es para guardar datos
 * el nombre del endpoint hace referencia a la identidad
 * del recurso que se esta creando, en este caso el usuario
*/
app.post('/user', (req, res) => {
    const data = req.body

    /*
     * Tienes mal el payload, los nombres de los campos no 
     * coinciden con los nombres de la request descritos en el
     * getDate() -> public/index.js
    */

    // const user = {
    //     nombre: data.nombre,
    //     fecha: data.fecha,
    //     color: data.color,
    //     calificacion: data.calificacion,
    //     telefono: data.telefono,
    //     correo: data.email,
    //     archivo: data.archivo,
    //     lenguaje: data.lenguaje
    // }

    console.log(req.body)

    const user = {
        nombre: data.name,
        fecha: data.date,
        color: data.color,
        calificacion: data.cal,
        telefono: data.tel,
        correo: data.emaill,
        archivo: data.file,
        lenguaje: data.language
    }

    db.insert(user, (err, doc) => { // insertar
        if (err) return console.log("Hubo un error")
        console.log('Usuario: ', doc.nombre, 'insertado.')
        res.send(doc) // Envia el documento insertado como respuesta
    })
});

// El listen siempre va abajo
app.listen(3001, () => console.log('Listening at port 3001'));
```

### Estructura de carpetas
La estructura ahora queda reorganizada de la siguiente manera:
![image](https://user-images.githubusercontent.com/32021976/170144063-c15630c8-ce31-47df-9ec6-5c7e5338746f.png)

# .gitignore

La carpeta de node_modules puede tener GIGAS de dependencias, para no subir todo esto a git (Por que luego que quieras clonarlo se va a ir todo eso tambien) recomiendo crear un archivo **.gitignore** en la raiz e ignorar la carepta de node_modules
![image](https://user-images.githubusercontent.com/32021976/170144442-033e9f37-8473-42e3-a000-047584afb574.png)

### Para eliminar la carpeta de node_modules que ya subiste, corre el siguiente comando en el root de tu proyecto
```sh
git rm node_modules
```

Que a sus ordenes para futuras dudas.

**Comment by ushieru** [comment]
# Como deberia verse su codigo al final?
![image](https://user-images.githubusercontent.com/32021976/170145069-126e271a-4256-4846-b10d-229d3995f190.png)

## index.js
```js
const express = require('express');
const app = express();
const Nedb = require('nedb')
const path = require('path')

app.use(express.static('public'));

const db = new Nedb({
    filename: path.join(__dirname, "usuarios.db"),
    autoload: true
})

app.get('/', (req, res) => {
    return res.sendFile(path.join(__dirname, '/index.html'));
})

app.use(express.json());

app.post('/user', (req, res) => {
    const data = req.body

    const user = {
        nombre: data.name,
        fecha: data.date,
        color: data.color,
        calificacion: data.cal,
        telefono: data.tel,
        correo: data.emaill,
        archivo: data.file,
        lenguaje: data.language
    }

    db.insert(user, (err, doc) => {
        if (err) {
            console.log("Hubo un error")
            return res.status(500).send("Hubo un error")
        }
        res.send(doc)
    })
});

app.listen(3001, () => console.log('Listening at port 3001'));
```

## index.html
```html 
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Formulario responsivo</title>
    <link rel="stylesheet" href="/styles.css">
    <script src="/index.js"></script>
</head>

<body>
    <form name="formulario" action="">
        <div class="contenedor">
            <div class="subcontenedor name">
                <input type="text" placeholder="Escribe tu nombre completo" required pattern="[aA-zZ]+" maxlength="100"
                    name="nombre" id="nombre">
            </div>

            <div class="subcontenedor date">
                <input type="date" name="fecha" id="fecha">
            </div>

            <div class="subcontenedor color"> Elige un color:
                <input type="color" name="color" id="color">
            </div>

            <div class="subcontenedor calificacion">
                <input type="number" name="calificacion" id="calificacion" placeholder="calificacion" step="1" max="100"
                    min="0">
            </div>

            <div class="subcontenedor file">
                <input type="file" name="archivo" id="archivo">
            </div>

            <div class="subcontenedor email">
                <input type="email" name="email" id="email" placeholder="email">
            </div>

            <div class="subcontenedor telefono">
                <input type="tel" name="telefono" id="telefono" placeholder="telefono" maxlength="10" pattern="[0-9]+">
            </div>

            <div class="subcontenedor languaje">
                <select name="lenguaje" id="lenguaje">
                    <option value="selecciona"> Selecciona un lenguaje </option>
                    <option value="java"> Java </option>
                    <option value="python"> Python </option>
                    <option value="c"> C </option>
                </select>
            </div>

            <input type="button" value="enviar" id="enviar" onclick="getData()">
            <input type="reset" value="limpiar" id="limpiar">
        </div>
    </form>
</body>

</html>
```

## public/index.js
```js
// Aqui va toda la logica de tu pagina

const getData = () => {
    var name = document.getElementById("nombre").value;
    var date = document.getElementById("fecha").value;
    var color = document.getElementById("color").value;
    var cal = document.getElementById("calificacion").value;
    var tel = document.getElementById("telefono").value;
    var emaill = document.getElementById("email").value;
    var file = document.getElementById("archivo").value;
    var language = document.getElementById("lenguaje").value;

    const data = { name, date, color, cal, tel, emaill, file, language };

    const options = {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(data)
    };

    fetch('/user', options)
        .then(response => response.json())
        .then(response => console.log(response))
}
```

## public/styles.css
```css
/* Aqui van todos los estilos de tu pagina*/
* {
    box-sizing: border-box;
}

body {
    font-family: Arial, Helvetica, sans-serif;
    background-color: rgb(187, 183, 183);
}

.contenedor {
    width: 800px;
    max-width: 100%;
    margin: 100px auto;
    margin-top: 100px;
    padding: 20px;
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 8px;
    /*box-shadow: 0 0 20px 1px rgb(0, 0, 0.3);*/
    /*border-radius: 10px;*/
}

.subcontenedor {
    background-color: gray;
    padding: 22px;
    border: white 5px solid;
    border-radius: 10px;
    cursor: pointer;
    color: white;
    text-align: center;
}

.subcontenedor:hover {
    background-color: black;
}

.name {
    background-color: darkorchid;
    grid-column: 1/4;
}

.date {
    background-color: orange;
}

.color {
    background-color: darkcyan;
}

.calificacion {
    background-color: darksalmon;
}

.telefono {
    background-color: green;
}

.email {
    background-color: rgb(241, 192, 28);
}

.file {
    background-color: brown;
    grid-column: 1/4;
}

.languaje {
    background-color: darkblue;
}

#enviar {
    background-color: black;
    color: white;
    border-radius: 7px;
}

#limpiar {
    background-color: black;
    color: white;
    border-radius: 7px;
}

#nombre {
    width: 70%;
}

#fecha {
    width: 100%;
}

#color {
    width: 100%;
}

#calificacion {
    width: 100%;
}

#archivo {
    width: 70%;
}

@media screen and (max-width: 912px) {
    .contenedor {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
    }

    .name {
        grid-column: 1/3;
    }

    .date {
        grid-column: 1/1;
    }

    .color {
        grid-column: 0/1;
    }

    .calificacion {
        grid-column: 1/1;
    }

    .email {
        grid-column: 1/3;
    }

    #email {
        width: 70%;
    }

    .file {
        grid-column: 1/3;
    }
}

@media screen and (max-width: 500px) {
    .contenedor {
        display: grid;
        grid-template-columns: 1fr;
    }

    .name,
    .date,
    .color,
    .calificacion,
    .telefono,
    .email,
    .file,
    .languaje {
        grid-column: 1/3;
    }

    #enviar {
        width: 200px;
    }

    #limpiar {
        width: 200px;
    }
}
```
